## code generated by chatGPT to resize a folder with images
from PIL import Image
import os

input_folder="inp/"
output_folder="outp/"
new_size=(800,600)

if not os.path.exists(output_folder):
	os.makedirs(output_folder)

for filename in os.listdir(input_folder):
	if filename.endswith('.png'):
		img_path=os.path.join(input_folder, filename)
		with Image.open(img_path) as img:
			img_resized=img.resize(new_size)
			output_path=os.path.join(output_folder, filename)
			img_resized.save(output_path)
		print(f"Image {filename} successfull resized and saved in outp Folder")