## code generated by ChatGPT to convert MP3 to .OGG Audio Files
from pydub import AudioSegment
import os

APV=os.getcwd()
def convert_wav_to_ogg(input_folder,output_folder,quality=5):
	if not os.path.exists(output_folder):
		os.makedirs(output_folder)
	for file_name in os.listdir(input_folder):
		if file_name.endswith('.mp3'):
			input_path=os.path.join(input_folder,file_name)
			output_path=os.path.join(output_folder,file_name.replace('.mp3','.ogg'))
			try:
				audio=AudioSegment.from_mp3(input_path)
				audio.export(output_path,format="ogg",codec="libvorbis",bitrate=f"{quality*16}k")
				print(f"Convert Audio: {file_name} -> {output_path}")
			except Exception as e:
				print(f"converting cancel: {file_name} #{e}")
input_folder=APV+'/mp3_folder'
output_folder=APV+'/ogg_folder'
convert_wav_to_ogg(input_folder,output_folder)
